apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
  name: product-query-bot
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/product-query-bot
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GOOGLE_API_KEY
          value: "YOUR_API_KEY_HERE"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
